// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sandbox.proto

package sandbox

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTotalNumParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTotalNumParams) Reset()         { *m = GetTotalNumParams{} }
func (m *GetTotalNumParams) String() string { return proto.CompactTextString(m) }
func (*GetTotalNumParams) ProtoMessage()    {}
func (*GetTotalNumParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_sandbox_1b74ac7e098419fd, []int{0}
}
func (m *GetTotalNumParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTotalNumParams.Unmarshal(m, b)
}
func (m *GetTotalNumParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTotalNumParams.Marshal(b, m, deterministic)
}
func (dst *GetTotalNumParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTotalNumParams.Merge(dst, src)
}
func (m *GetTotalNumParams) XXX_Size() int {
	return xxx_messageInfo_GetTotalNumParams.Size(m)
}
func (m *GetTotalNumParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTotalNumParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetTotalNumParams proto.InternalMessageInfo

type AddNumParams struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNumParams) Reset()         { *m = AddNumParams{} }
func (m *AddNumParams) String() string { return proto.CompactTextString(m) }
func (*AddNumParams) ProtoMessage()    {}
func (*AddNumParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_sandbox_1b74ac7e098419fd, []int{1}
}
func (m *AddNumParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNumParams.Unmarshal(m, b)
}
func (m *AddNumParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNumParams.Marshal(b, m, deterministic)
}
func (dst *AddNumParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNumParams.Merge(dst, src)
}
func (m *AddNumParams) XXX_Size() int {
	return xxx_messageInfo_AddNumParams.Size(m)
}
func (m *AddNumParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNumParams.DiscardUnknown(m)
}

var xxx_messageInfo_AddNumParams proto.InternalMessageInfo

func (m *AddNumParams) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type TotalNum struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalNum) Reset()         { *m = TotalNum{} }
func (m *TotalNum) String() string { return proto.CompactTextString(m) }
func (*TotalNum) ProtoMessage()    {}
func (*TotalNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_sandbox_1b74ac7e098419fd, []int{2}
}
func (m *TotalNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalNum.Unmarshal(m, b)
}
func (m *TotalNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalNum.Marshal(b, m, deterministic)
}
func (dst *TotalNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalNum.Merge(dst, src)
}
func (m *TotalNum) XXX_Size() int {
	return xxx_messageInfo_TotalNum.Size(m)
}
func (m *TotalNum) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalNum.DiscardUnknown(m)
}

var xxx_messageInfo_TotalNum proto.InternalMessageInfo

func (m *TotalNum) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*GetTotalNumParams)(nil), "sandbox.getTotalNumParams")
	proto.RegisterType((*AddNumParams)(nil), "sandbox.addNumParams")
	proto.RegisterType((*TotalNum)(nil), "sandbox.totalNum")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddNumServiceClient is the client API for AddNumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddNumServiceClient interface {
	AddNum(ctx context.Context, in *AddNumParams, opts ...grpc.CallOption) (*TotalNum, error)
	GetTotalNum(ctx context.Context, in *GetTotalNumParams, opts ...grpc.CallOption) (*TotalNum, error)
}

type addNumServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddNumServiceClient(cc *grpc.ClientConn) AddNumServiceClient {
	return &addNumServiceClient{cc}
}

func (c *addNumServiceClient) AddNum(ctx context.Context, in *AddNumParams, opts ...grpc.CallOption) (*TotalNum, error) {
	out := new(TotalNum)
	err := c.cc.Invoke(ctx, "/sandbox.addNumService/addNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addNumServiceClient) GetTotalNum(ctx context.Context, in *GetTotalNumParams, opts ...grpc.CallOption) (*TotalNum, error) {
	out := new(TotalNum)
	err := c.cc.Invoke(ctx, "/sandbox.addNumService/getTotalNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddNumServiceServer is the server API for AddNumService service.
type AddNumServiceServer interface {
	AddNum(context.Context, *AddNumParams) (*TotalNum, error)
	GetTotalNum(context.Context, *GetTotalNumParams) (*TotalNum, error)
}

func RegisterAddNumServiceServer(s *grpc.Server, srv AddNumServiceServer) {
	s.RegisterService(&_AddNumService_serviceDesc, srv)
}

func _AddNumService_AddNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNumParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddNumServiceServer).AddNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.addNumService/AddNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddNumServiceServer).AddNum(ctx, req.(*AddNumParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddNumService_GetTotalNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalNumParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddNumServiceServer).GetTotalNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.addNumService/GetTotalNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddNumServiceServer).GetTotalNum(ctx, req.(*GetTotalNumParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddNumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.addNumService",
	HandlerType: (*AddNumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addNum",
			Handler:    _AddNumService_AddNum_Handler,
		},
		{
			MethodName: "getTotalNum",
			Handler:    _AddNumService_GetTotalNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox.proto",
}

func init() { proto.RegisterFile("sandbox.proto", fileDescriptor_sandbox_1b74ac7e098419fd) }

var fileDescriptor_sandbox_1b74ac7e098419fd = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0xcc, 0x4b,
	0x49, 0xca, 0xaf, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x84, 0xb9,
	0x04, 0xd3, 0x53, 0x4b, 0x42, 0xf2, 0x4b, 0x12, 0x73, 0xfc, 0x4a, 0x73, 0x03, 0x12, 0x8b, 0x12,
	0x73, 0x8b, 0x95, 0xd4, 0xb8, 0x78, 0x12, 0x53, 0x52, 0xe0, 0x7c, 0x21, 0x31, 0x2e, 0xb6, 0xbc,
	0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x49, 0x81,
	0x8b, 0xa3, 0x04, 0xaa, 0x53, 0x48, 0x84, 0x8b, 0x15, 0xcc, 0x86, 0x2a, 0x81, 0x70, 0x8c, 0x5a,
	0x19, 0xb9, 0x78, 0x21, 0x46, 0x05, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x99, 0x70, 0xb1,
	0x41, 0x04, 0x84, 0x44, 0xf5, 0x60, 0x6e, 0x42, 0xb6, 0x4c, 0x4a, 0x10, 0x2e, 0x0c, 0x33, 0x5b,
	0x89, 0x41, 0xc8, 0x8e, 0x8b, 0x1b, 0xc9, 0x99, 0x42, 0x52, 0x70, 0x35, 0x18, 0x8e, 0xc7, 0xaa,
	0x3f, 0x89, 0x0d, 0xec, 0x6d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x56, 0x3b, 0x30,
	0x07, 0x01, 0x00, 0x00,
}
